// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	NOTION_REDIRECT_URI: "https://auth.notero.vanoni.dev";
	NOTION_CLIENT_ID: string;
	NOTION_CLIENT_SECRET: string;
}
