name = "notero-auth"
main = "src/notion-oauth-login.ts"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[observability]
enabled = true

[[routes]]
pattern = "auth.notero.vanoni.dev"
custom_domain = true

[vars]
NOTION_REDIRECT_URI = "https://auth.notero.vanoni.dev"
